apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: aletheia
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/part-of: aletheia
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: config-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: config-server
    spec:
      containers:
        - name: config-server
          image: manef99/config-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9999

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: aletheia
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/part-of: aletheia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: config-server
  ports:
    - name: http
      port: 9999
      targetPort: http