apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses
  namespace: aletheia
  labels:
    app.kubernetes.io/name: courses
    app.kubernetes.io/part-of: aletheia
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: courses
  template:
    metadata:
      labels:
        app.kubernetes.io/name: courses
    spec:
      containers:
        - name: courses
          image: manef99/courses:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081

          env:
            - name: SERVER_PORT
              value: "8081"

            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:9999"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-courses:3306/course_management?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"

            - name: SPRING_DATASOURCE_USERNAME
              value: "root"

            - name: SPRING_DATASOURCE_PASSWORD
              value: ""

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka"

            - name: EUREKA_INSTANCE_HOSTNAME
              value: "courses"

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 8

          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 5

          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "768Mi"
              cpu: "700m"

---
apiVersion: v1
kind: Service
metadata:
  name: courses
  namespace: aletheia
  labels:
    app.kubernetes.io/name: courses
    app.kubernetes.io/part-of: aletheia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: courses
  ports:
    - name: http
      port: 8081
      targetPort: http