  apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-user-pvc
  namespace: aletheia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user
  namespace: aletheia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
        - name: mysql-user
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ""
            - name: MYSQL_DATABASE
              value: alethia

          volumeMounts:
            - name: mysql-user-storage
              mountPath: /var/lib/mysql

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20

      volumes:
        - name: mysql-user-storage
          persistentVolumeClaim:
            claimName: mysql-user-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-user
  namespace: aletheia
spec:
  type: ClusterIP
  selector:
    app: mysql-user
  ports:
    - port: 3306
      targetPort: 3306