services:
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "9999:9999"
    depends_on:
      - eureka

  api-gateway:
    build: ./ApiGateway
    container_name: api-gateway
    ports:
      - "8089:8089"
    depends_on:
      - config-server

  mysql-courses:
    image: mysql:8.0
    container_name: mysql-courses
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: course_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_courses_data:/var/lib/mysql

  courses-service:
    build: ./microservices/courses
    container_name: courses-service
    ports:
      - "8081:8081"
    depends_on:
      - api-gateway
      - mysql-courses
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:9999

volumes:
  mysql_courses_data:
