############################
### SERVER
############################

spring.application.name=aletheia-platform

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:9999
app.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_123456