spring.application.name=eureka

# Specifies the port on which the Eureka Server will run
server.port=8761

# Prevents the Eureka Server from registering itself as a client
eureka.client.register-with-eureka=false

# Prevents the Eureka Server from fetching the registry from other Eureka servers
eureka.client.fetch-registry=false

# ===============================
# ACTUATOR / PROMETHEUS
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true