spring.application.name=courses-service

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:9999


app.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_123456
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skanderferjani07@gmail.com
spring.mail.password=jxfbyqofrgogxaia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true