spring.application.name=ApiGateway
server.port=8089

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

logging.level.org.springframework.cloud.gateway=INFO
# Keep logging levels for debugging
logging.level.reactor.netty.http.client=WARN

spring.cloud.gateway.discovery.locator.enabled=false

# Allow large file uploads through gateway
spring.codec.max-in-memory-size=50MB

#  User Service (port 8080)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/admin/users/**

# Courses Service (port 8081)
spring.cloud.gateway.routes[1].id=courses-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**,/api/lessons/**,/api/enrollments/**,/api/certificates/**,/api/instructor/**,/api/admin/**,/course/**,/api/formations/**

# Library Service (port 8082)
spring.cloud.gateway.routes[2].id=library-service
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/products/**,/api/cart/**,/api/orders/**,/api/receipts/**,/api/stock-movements/**,/api/loans/**,/api/files/**,/api/borrowing-policies/**,/api/analytics/**

#  Events Service (port 8090)
spring.cloud.gateway.routes[3].id=events-service
spring.cloud.gateway.routes[3].uri=http://localhost:8090
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/events/**,/api/allocations/**,/api/resources/**,/room/**,/ws/**

#  Offer Service (port 8086)
spring.cloud.gateway.routes[4].id=offer-service
spring.cloud.gateway.routes[4].uri=http://localhost:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/offers/**,/api/coupons/**,/api/flash-sales/**,/api/subscriptions/**,/api/subscription-plans/**,/api/offer-analytics/**

# Resource Management Service (port 8094)
spring.cloud.gateway.routes[5].id=resource-management-service
spring.cloud.gateway.routes[5].uri=http://localhost:8094
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/rm/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/api/rm/(?<segment>.*), /api/$\{segment}
