spring.application.name=ApiGateway
server.port=8089

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

# Keep logging levels for debugging
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.reactor.netty.http.client=WARN

# Since you are defining routes manually in Java, keep this false
spring.cloud.gateway.discovery.locator.enabled=false

