<<<<<<< HEAD
spring.application.name=ApiGateway
server.port=8089

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=WARN

spring.cloud.gateway.discovery.locator.enabled=false
=======
# Application name (must match Eureka registration)
spring.application.name=ApiGateway

server.port=8089

#EUREKA_Registery
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Log routes
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG




# Enable discovery-based routing (optional)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# Route 1 - Library Service
spring.cloud.gateway.routes[0].id=library-service
spring.cloud.gateway.routes[0].uri=lb://library-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/library/**


spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true


>>>>>>> origin/course-managment

