CREATE DATABASE IF NOT EXISTS alethia;
CREATE DATABASE IF NOT EXISTS course_management;
CREATE DATABASE IF NOT EXISTS aletheia_library;
CREATE DATABASE IF NOT EXISTS event_db;
CREATE DATABASE IF NOT EXISTS aletheia_resources;
